#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "180px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Bigspring"
# theme-mode
theme_switcher = true
theme_default = "system" # available options [light/dark/system]
# Main Sections
mainSections = ["blog"]
# contact form action
contact_form_action = "#!" # contact form works with [https://airform.io/] or [https://formspree.io]
# demo form action
demo_form_action = "#!" # demo form works with [https://airform.io/] or [https://formspree.io]
# career form action
career_form_action = "#"
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "" # example: G-XXXXXXXXXX
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script = ""
# copyright
theme_copyright = true
copyright = "Copyright by your company"

# preloader
# preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format. example - "images/preloader.gif"

# Navigation buttons
[navigation_button]
enable = true
label = "Get Started"
link = "contact"


# crisp chat
# crisp chat module: https://github.com/gethugothemes/hugo-modules/tree/master/components/crisp-chat
[crisp_chat]
enable = false
crisp_website_id = "9aa449e1-9999-422a-938f-8567982eec6d" # replace this code with yours
# Check this video tutorial to get your crisp website ID - https://www.youtube.com/watch?v=nW5UX6iVdFc

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Hugo", "Themefisher", "Gethugothemes"]
description = "This is meta description"
author = "Gethugothemes"
image = "images/logo.png"                           # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
# matomo tracking module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/matomo-analytics
[matomo]
enable = false
url = ""       # your matomo url
id = ""        # your matomo id

# baidu analytics: see https://tongji.baidu.com/
# baidu analytics module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/baidu-analytics
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
# plausible analytics module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/plausible-analytics
[plausible]
enable = false
domain = ""    # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
# counter analytics module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/counter-analytics
[counter]
enable = false
username = ""  # your username

# site verifications
# site verifications module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

############################# social site ########################
[[social]]
title = "facebook"
icon = "fab fa-facebook" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#!"

[[social]]
title = "twitter"
icon = "fab fa-twitter" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#!"

[[social]]
title = "instagram"
icon = "fab fa-instagram" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#!"

[[social]]
title = "github"
icon = "fab fa-github" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#!"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin" # fontawesome icon pack : https://fontawesome.com/icons/
link = "#!"
