######################## default configuration ####################
baseURL = "http://demo.gethugothemes.com/bigspring-light/examplesite/"
title = "Bigspring Light"
theme = "bigspring-light"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true