[de]
contentDir = ""
copyright = ""
footer_content = ""
footer_menu_left = ""
footer_menu_middle = ""
footer_menu_right = ""
languageName = ""
title = ""
weight = ""
[en]
contentDir = "content/english"
copyright = "Design By [Themefisher](https://themefisher.com/) Develop By [Gethugothemes](https://gethugothemes.com/)"
footer_content = ""
footer_menu_left = "Empresa"
footer_menu_middle = "Vistos AUS"
footer_menu_right = "Contato"
languageName = "En"
title = "Imigração para Austrália"
weight = 1
