[[footer_left]]
name = "About Us"
url = "#"
[[footer_left]]
name = "Quick Start"
url = "#"
[[footer_left]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Pricing"
url = "pricing"
[[footer_middle]]
name = "Platform"
url = "#"
[[footer_middle]]
name = "Features"
url = "#"
[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy"
[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions"
[[footer_right]]
name = "FAQ"
url = "faq"
[[main]]
name = "Home"
url = "/"
weight = 1
[[main]]
name = "Imigração"
url = "imigração"
weight = 2
[[main]]
name = "Vistos AUS"
url = "vistos aus"
weight = 3
[[main]]
name = "Empresa"
url = "empresa"
weight = 5
[[main]]
name = "Depoimentos"
url = "depoimentos"
weight = "5"
[[main]]
name = "Contato"
url = "contato"
weight = "6"
