author = "Themefisher"
contact_form_action = "#"
description = "Imigração para Austrália - Trabalhar na Austrália"
image = "images/SMART_VISTOS_logowebsite.png"
logo = "images/SMART_VISTOS_logowebsite.png"
logo_width = "250px"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[navigation_button]
enable = false
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/smartvistos"
title = "facebook"
[[social]]
icon = "fab fa-whatsapp"
link = "http://api.whatsapp.com/send?phone=5519971511269"
title = "whatsapp"
[[social]]
icon = "fab fa-linkedin"
link = "linkedin.com/in/marcelo-mota-fukuoka-2514b0"
title = "linkedin"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
