author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
image = "images/logo.png"
logo = "images/flamingo_menu_logo.png"
logo_width = "200px"
social = []
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[navigation_button]
enable = true
label = "Get Started"
link = "contact"
[preloader]
enable = true
preloader = ""
