author = "Themefisher"
contact_form_action = "#"
description = "This is meta description"
image = "images/SMART VISTOS LOGO OFICIAL.jpg"
logo = "images/SMART VISTOS LOGO OFICIAL.jpg"
logo_width = "200px"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[navigation_button]
enable = false
label = "Get Started"
link = "contact"
[preloader]
enable = false
preloader = ""
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/smartvistos"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-skype"
link = "#"
title = "skype"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
