---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: exampleSite/data/en/homepage.yml
  label: Homepage Data (en)
- type: document
  path: exampleSite/data/fr/homepage.yml
  label: Homepage Data (fr)
- type: heading
  label: Blog Post
- type: document
  path: exampleSite/content/english/blog/_index.md
  label: Blog Page (en)
- type: document
  path: exampleSite/content/french/blog/_index.md
  label: Blog Page (fr)
- type: directory
  path: exampleSite/content/english/blog
  label: Post (en)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: directory
  path: exampleSite/content/french/blog
  label: Post (fr)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: FAQ
- type: directory
  path: exampleSite/content/english/faq
  label: FAQ (en)
  create: documents
  match: "**/*"
- type: directory
  path: exampleSite/content/french/faq
  label: FAQ (fr)
  create: documents
  match: "**/*"
- type: heading
  label: Pricing
- type: directory
  path: exampleSite/content/english/pricing
  label: Pricing (en)
  create: documents
  match: "**/*"
- type: directory
  path: exampleSite/content/french/pricing
  label: Pricing (fr)
  create: documents
  match: "**/*"
- type: heading
  label: Career
- type: directory
  path: exampleSite/content/english/career
  label: Career (en)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/french/career
  label: Career (fr)
  create: all
  match: "**/*"
- type: heading
  label: About
- type: directory
  path: exampleSite/content/english/about
  label: About (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/about
  label: About (fr)
  create: none
  match: "*"
- type: heading
  label: Contact
- type: directory
  path: exampleSite/content/english/contact
  label: Contact (en)
  create: none
  match: "*"
- type: directory
  path: exampleSite/content/french/contact
  label: Contact (fr)
  create: none
  match: "*"
- type: heading
  label: Service
- type: directory
  path: exampleSite/content/english/service
  label: Service (en)
  create: documents
  match: "**/*"
- type: directory
  path: exampleSite/content/french/service
  label: Service (fr)
  create: all
  match: "**/*"
- type: heading
  label: Team
- type: directory
  path: exampleSite/content/english/team
  label: Team (en)
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/french/team
  label: Team (fr)
  create: all
  match: "**/*"
- type: heading
  label: All Pages
- type: directory
  path: exampleSite/content/english
  label: All Pages (en)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: directory
  path: exampleSite/content/french
  label: All Pages (fr)
  create: all
  match: "**/*"
  templates:
  - new-page
- type: heading
  label: Configuration
- type: directory
  path: exampleSite/i18n
  label: i18n
  create: documents
  match: "**/*"
- type: document
  path: exampleSite/config.toml
  label: Configuration
upload_dir: exampleSite/static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
