######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/bigspring/site/"
title = "Bigspring Light"
theme = "bigspring-light"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "America/New_York"
# post pagination
pagination.pagerSize = 3
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# disable language
disableLanguages = [
] # example: ["de"] for disable deutsch language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = true # If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content.

########################### Services #############################
[services]
[services.googleAnalytics]
ID = '##########' # see https://gohugo.io/templates/internal/#configure-google-analytics


############################# Modules ############################
[module]
[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "hugo_stats.json"
target = "assets/watching/hugo_stats.json"


############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "Lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"

######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#0AA8A7"
color_secondary = "#376f92"
body_color = "#fff"
text_color = "#777"
text_dark = "#222"
text_light = "#959595"
border_color = "#ECECEC"
dark_body_color = "#1E262C"
dark_text_color = "#cbcbcb"
dark_text_light = "#959595"
dark_text_dark = "#fff"
dark_border_color = "#4e4e4e"
black = "#101418"
white = "#fff"
light = "#EDF6F5"
dark = "#1b2229"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Lato:wght@300;400;500;600;700"
font_primary_type = "sans-serif"           # [serif/sans-serif]
font_icon = "Font Awesome 6 Free"          # https://fontawesome.com/v5.15/icons/


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/swiper/swiper-bundle.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/regular.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"


# JS Plugins
[[params.plugins.js]]
link = "plugins/swiper/swiper-bundle.js"
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
[[params.plugins.js]]
link = "plugins/cookie.js"
[[params.plugins.js]]
link = "plugins/lazy-loader.js"
[[params.plugins.js]]
link = "js/tab.js"

